---
apiVersion: v1
kind: Namespace
metadata:
  name: pacman-dev
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
